SELECT P_CODE, P_DESCRIPT, P_CATEGORY, V_NAME, V_AREACODE, V_STATE, CUS_CODE, CUS_LNAME, CUS_FNAME, CUS_INITIAL, CUS_STATE, REG_NAME, TM_YEAR, TM_MONTH, TM_DAY, TM_QTR, SALE_UNITS, SALE_PRICE, (SALE_UNITS * SALE_PRICE) AS SALE_TOTAL
FROM DWDAYSALESFACT JOIN DWTIME USING (TM_ID) 
     JOIN DWCUSTOMER USING (CUS_CODE)
     JOIN DWREGION USING (REG_ID)
     JOIN DWPRODUCT USING (P_CODE)
     JOIN DWVENDOR USING (V_CODE);
