create table customer (
CUST_NUM INT(11) PRIMARY KEY,
CUST_LNAME VARCHAR(30),
CUST_FNAME VARCHAR(30),
CUST_BALANCE DECIMAL(8,2)
);

create table invoice (
INV_NUM INT(11) PRIMARY KEY,
CUST_NUM INT(11),
INV_DATE DATE,
INV_AMOUNT DECIMAL(10,2),
FOREIGN KEY (CUST_NUM) REFERENCES CUSTOMER(CUST_NUM)
);