select EMP_NUM, EMP_LNAME, EMP_FNAME, SAL_FROM, SAL_END, SAL_AMOUNT
from LGEMPLOYEE
	join LGSALARY_HISTORY using (EMP_NUM)
where EMP_NUM = 83731 or EMP_NUM = 83745 or EMP_NUM = 84039
order by EMP_NUM, SAL_FROM;