select LGPRODUCT.BRAND_ID, BRAND_NAME, BRAND_TYPE, format(max(PROD_PRICE), 2) as "AVGPRICE"
from LGPRODUCT
	join LGBRAND on LGPRODUCT.BRAND_ID = LGBRAND.BRAND_ID
group by LGPRODUCT.BRAND_ID
having AVGPRICE =
	(select max(AVG_PRICE)
	from (select BRAND_ID, avg(PROD_PRICE) as AVG_PRICE
	from LGPRODUCT
	group by BRAND_ID
	) as BRAND_AVG);